### ISSUE TITLE
No Styling on GNOME Clocks Timer

### ISSUE THREAD

**Issue by deadite81** [numixproject/numix-gtk-theme#137]
What I am using:
Arch Linux
GNOME 3.12
GNOME Clocks 3.12.0
Numix from Git

The progress circle in the program GNOME Clocks has no styling.

Adwaita:
![screenshot from 2014-05-21 00 12 07](https://cloud.githubusercontent.com/assets/231300/3036031/c08cf77e-e09e-11e3-997f-83bfd591c582.png)

Numix:
![screenshot from 2014-05-21 00 12 25](https://cloud.githubusercontent.com/assets/231300/3036032/cb725490-e09e-11e3-9e70-dcbdd6d528bd.png)

Thanks for your continued work on this great theme.

**Comment by satya164** [comment]
Thanks. Will look into it.

**Comment by khurshid-alam** [comment]
This needs to fixed in Gtk 3.18 as well.

**Comment by bilelmoussaoui** [comment]
Fixed here, i'm using Gnome Clocks 3.18.0
![capture du 2016-03-08 00-09-10](https://cloud.githubusercontent.com/assets/7660997/13586566/01ebd5ae-e4c2-11e5-8a9e-1d8584901ad9.png)

**Comment by megax** [comment]
@satya164 @khurshid-alam gtk 3.20 fixed: 
![image](https://cloud.githubusercontent.com/assets/461493/17869435/839494e0-68b3-11e6-8ba7-f5341a4051d3.png)

**Comment by khurshid-alam** [comment]
@megax Stopwatch needs to be themed. It looks odd. https://github.com/GNOME/gnome-clocks/blob/master/data/css/gnome-clocks.css

**Comment by megax** [comment]
Adwaita theme:
![image](https://cloud.githubusercontent.com/assets/461493/17871833/95db03fa-68bd-11e6-82ee-c2cccccc0f34.png)

**Comment by megax** [comment]
@khurshid-alam Exactly what he meant?

**Comment by khurshid-alam** [comment]
@megax I wanted to make the color semi-circular radial (which rotates) red. Darker shade (of $selected_bg_color) for smaller **minute** semi circle and lighter shade for bigger **second** semi circle. Anyway its a design issue.

Mockup: 

![gnome-clock-mockup](http://i.imgur.com/na0QZdt.png)

**Comment by megax** [comment]
In principle, it should be amended. But it's not working.

```
.clocks-analog-frame.trough {
    color: mix(@theme_fg_color, @theme_bg_color, 0.85);
}

.clocks-analog-frame.progress {
    color: mix(@theme_fg_color, @theme_bg_color, 0.5);
}

.clocks-analog-frame.progress-fast {
    color: @theme_fg_color;
}
```

**Comment by khurshid-alam** [comment]
@megax You are using wrong color values. Try this (& lighten/darken color):

``` css
.clocks-analog-frame.trough {
    color: mix(@theme_fg_color, @theme_bg_color, 0.85);
}

.clocks-analog-frame.progress {
    color: shade(@theme_selected_bg_color, 1.1);
}

.clocks-analog-frame.progress-fast {
    color: shade(@theme_selected_bg_color, .7);
}
```

![gnome-clock-mockup1](http://i.imgur.com/f5rjDpn.png)
