### ISSUE TITLE
Weird transparent section in some Gtk(3.12) apps on Ubuntu Utopic

### ISSUE THREAD

**Issue by khurshid-alam** [numixproject/numix-gtk-theme#166]
I have tested this with Numix from Ubuntu repo, ppa version & from github. Application with gtk-headerbar has weird transparent section.
1. Gnome-Tweak-Tool: 
   If I open it & change tabs, some of the middle section gets transparent. 
   ![teak-tool](http://i.imgur.com/8Hgn8dp.png)

If change (in gtk-widgets.css)

``` css
GtkGrid:insensitive {
    background-color: transparent;
}
```

to

``` css
GtkGrid:insensitive {
    background-color: @theme_bg_color;
}
```

it **fixes the issue , but then tabs button gets messed up**.
1. Baobab (Gnome Disk Analyzer) (3.12.x)

![baobab](http://i.imgur.com/AHOMSYL.png)

Even though unity decorator & compiz officially doesn't officially support headerbar decoration, I can reproduce it in other desktop shell/session as well like (gnome-flashback-metacity, gnome-flashback-compiz).

And It doesn't happen with Ambiance (even though headerbar apps apppears border-less & shadow less with it.)
