### ISSUE TITLE
Desktop shortcut labels unreadable on Mint OS

### ISSUE THREAD

**Issue by donaldrobertson** [numixproject/numix-gtk-theme#194]
Okay, third time lucky (at finding the right place to raise a bug report)...  

I'm using Linux Mint and the text labels under desktop shortcuts (launchers) appear too dark to read (dark grey) unless I change the theme setting for "controls" back from Numix to Mint-X, which makes the text white again.  Is there a workaround for this?

**Comment by Tux1** [comment]
Go to /usr/share/themes/Numix/gtk-3.0/apps/nemo.css 
and append  

`````` css
.nemo-desktop.nemo-canvas-item {
    color: white;
    text-shadow: 1px 1px black;
}

.nemo-desktop.nemo-canvas-item:active {
    color: @theme_fg_color;
}

.nemo-desktop.nemo-canvas-item:selected {
    color: @theme_selected_fg_color;
}

.nemo-desktop.nemo-canvas-item:active,
.nemo-desktop.nemo-canvas-item:prelight,
.nemo-desktop.nemo-canvas-item:selected {
    text-shadow: none;
}```
``````
