### ISSUE TITLE
Transparent tooltip-background on Fedora's firefox >= 37

### ISSUE THREAD

**Issue by HeikoAdams** [numixproject/numix-gtk-theme#225]
Since version 37 firefox on linux supports transparent backgrounds which causes the tooltips of firefox tabs ATM beeing unreadable

**Comment by SemaiCZE** [comment]
Yes, I confirm this problem on Fedora 22 with Gnome 3.16. Workaround for now is to add these lines to your ~/.config/gtk-3.0/gtk.css:

``` css
.tooltip {
  color: @tooltip_fg_color;
  padding: 4px;
  border-radius: 5px;
  box-shadow: none;
  text-shadow: 0 1px black;
}
.tooltip.background {
  background-color: @tooltip_bg_color;
  background-clip: padding-box;
  border: 1px solid rgba(255, 255, 255, 0.1);
}
.tooltip.window-frame.csd {
  background-color: transparent;
}
.tooltip * {
  padding: 4px;
  background-color: transparent;
  color: inherit;
}
```
