### ISSUE TITLE
Notifications background is transparent in elementaryOS 0.3

### ISSUE THREAD

**Issue by f-f** [numixproject/numix-gtk-theme#238]
As of elementaryOS 0.3, the notifications with the Numix GTK theme are shown with a transparent background. This can be a problem on white backgrounds (like webpages, pdfs, basically everything) as also the font color is white.

![screenshot from 2015-07-24 19 18 43](https://cloud.githubusercontent.com/assets/5480361/8880413/d7dd279a-3238-11e5-83fd-9bb59a8281f0.png)

**Comment by satya164** [comment]
There is no Pantheon support as of now. Feel free to send pull requests to the sass branch.

**Comment by HeyDSN** [comment]
maybe this will help.
add this line at the end of file /usr/share/themes/Numix Daily/gtk-3.0/apps/gnome-applications.css

``` css
/******************
** custom -fix**
*******************/
/***********
** Gala **
************/

.gala-notification {
    border: none;
    border-radius: 4px;
    background-color: transparent;
    background-image: linear-gradient(to bottom,
                                  alpha (@bg_color, 0.98),
                                  alpha (@bg_color, 0.98) 80%,
                                  alpha (shade(@bg_color, 0.94), 0.98)
                                  );
    box-shadow: inset 0 0 0 1px alpha (@bg_highlight_color, 0.10),
                inset 0 1px 0 0 alpha (@bg_highlight_color, 0.90),
                inset 0 -1px 0 0 alpha (@bg_highlight_color, 0.30),
                0 0 0 1px alpha (#000, 0.20),
                0 3px 6px alpha (#000, 0.16),
                0 3px 6px alpha (#000, 0.23);
}

.gala-notification .title, .gala-notification .label {
    color: @text_color;
}

.gala-button {
    padding: 3px;
    color: #fff;
    border: none;
    border-radius: 100px;
    background-image: linear-gradient(to bottom,
                                  #7e7e7e,
                                  #3e3e3e
                                  );
    box-shadow: inset 0 0 0 1px alpha (#fff, 0.02),
                inset 0 1px 0 0 alpha (#fff, 0.07),
                inset 0 -1px 0 0 alpha (#fff, 0.01),
                0 0 0 1px alpha (#000, 0.40),
                0 3px 6px alpha (#000, 0.16),
                0 3px 6px alpha (#000, 0.23);
    text-shadow: 0 1px 1px alpha (#000, 0.6);
}

/*************
** Geary **
*************/

ConversationListView {
    -GtkWidget-focus-line-width: 1px;
    -GtkTreeView-grid-line-width: 0;
}

ConversationListView.view.cell {
    border-style: solid;
    border-width: 0 0 1px 0;
    border-color: alpha (#000, 0.2);
}

ConversationListView.view.cell:selected:focus {
    border-style: solid;
    border-width: 0 0 1px 0;
    border-color: shade (@colorAccent, 0.8);
}
```

![screenshot from 2015-12-16 22 50 24](https://cloud.githubusercontent.com/assets/15194086/11845697/ac66dbfc-a447-11e5-9bac-97721f0496ce.png)
