### ISSUE TITLE
Numix doesn't work with some applications in Ubuntu 15.10

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-gtk-theme#258]
Hi,

In Ubuntu 15.10 some applications (seems to be those using client side decorations) will look ugly when Numix GTK theme is enabled.. An example is MenuLibre (see screenshot). These applications get a wide gray frame outside the actual window. With the default theme the applications looks normal.

![mlnumix1](https://cloud.githubusercontent.com/assets/1281031/10555498/2482a47a-743e-11e5-95b7-1cb5f406c944.png)

**Comment by wldcordeiro** [comment]
Just noticed this as well. Seems like extra margin or something odd.

**Comment by LeartS** [comment]
I have the same issues. It seems to happen with gnome apps using client side decorations / headerbars. You can partially fix it following the instructions here: https://wiki.archlinux.org/index.php/GTK%2B#Client-side_decorations

EDIT: duplicate of https://github.com/shimmerproject/Numix/issues/206

**Comment by wldcordeiro** [comment]
@LeartS That does a decent job but then the topbar is white for some apps.

**Comment by LeartS** [comment]
@wldcordeiro Yes, it actually did the same to me.
Now I'm using just this:

``` css
.window-frame.solid-csd {
    border: solid 1px alpha(black, 0.7);
    border: solid 1px shade(@theme_bg_color, 0.5);
    border-radius: 0;
    margin: 0px;
    background-color: black;
    box-shadow: none;
}
```

Which actually looks better and doesn't seem to interfere with other apps (but I've not tested it extensively)
