### ISSUE TITLE
GTK 3.20 :: Baobab progress bug (backdrop mode)

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#447]
![anim](https://cloud.githubusercontent.com/assets/461493/15287026/8477f29e-1b60-11e6-9faf-e0e7ace37f90.gif)

**Comment by megax** [comment]
Tested GTK 3.18 (ubuntu 16.04):
![anim](https://cloud.githubusercontent.com/assets/461493/15287362/97451472-1b62-11e6-9b23-d0bdbcb80028.gif)

**Comment by khurshid-alam** [comment]
@megax This is our old baobab code (css). Change color values and see if it works.

``` css
.cell.baobab-level-cell,
.cell.baobab-level-cell:hover,
.cell.baobab-level-cell:selected,
.cell.baobab-level-cell:selected:hover {
    border-color: shade(@theme_bg_color, .8);
    border-width: 1px;
    border-radius: 2px;
    border-style: solid;
    padding: 1px;
    background-color: shade(@theme_bg_color, 1.08);
}

.cell.baobab-level-cell.fill-block,
.cell.baobab-level-cell.fill-block:selected,
.cell.baobab-level-cell.fill-block:selected:hover {
    background-color: #edd400;
}

.cell.baobab-level-cell.fill-block.level-low,
.cell.baobab-level-cell.fill-block.level-low:hover {
    background-color: #73d216;
}

.cell.baobab-level-cell.fill-block.level-high,
.cell.baobab-level-cell.fill-block.level-high:hover {
    background-color: #cc0000;
}

.cell.baobab-cell-error {
    color: @error_color;
}

.cell.baobab-cell-warning {
    color: @warning_color;
}

.cell.baobab-cell-warning:selected,
.cell.baobab-cell-error:selected {
    color: @theme_selected_fg_color;
}

window.background stack > grid > scrolledwindow.frame {
    border-radius: 0;
    border-width: 0 1px 0 0;
}

window infobar.warning,
window infobar.error {
    border-bottom-width: 1px;
    border-bottom-style: solid;
    border-bottom-color: shade(@theme_bg_color, .8);
}

ringschart {
    padding: 13px 13px 13px 13px;
}

ringschart.subfolder-tip {
    color: white;
    background-color: rgba(0, 0, 0, 0.8);
    border-radius: 3px;
    padding: 3px 3px 3px 3px;
}
```

If it works, then create a seperate `_baobab.scss` and import that in `_widgets.scss`.
